### ISSUE TITLE
dataset automation

### ISSUE THREAD

**Issue by AcckiyGerman** [datasets/gdp-us#2]
I want to automate this dataset so I'm making progress for https://github.com/datahq/pm/issues/78

## tasks

* [ ] automate the dataset using `flow.yaml`

## Analyse
The current script wrangling operations is following (below is source files, upon - result files):
![gdp-us](https://user-images.githubusercontent.com/11707682/34669342-6d1047fa-f471-11e7-8888-27b2aaa231ed.png)

## Algorithm 
* split each source into 2 tables (annual, quarterly)
    * create 4 intermediate resources
    * use dpp to split data - which is it not possible ATM (jan2018)
    * save tables into resources
* merge pairs of intermediate tables into two files: (annual, quarterly)
    * align files by dates **atm result table is not aligned which is incorrect**  (how to do that?)
    * merge tables using dpp

**Comment by AcckiyGerman** [comment]
ATM I've stack trying to make a `spec.yaml` for dpp, coz it requires python3.6 and it appears not so easy to install in ubuntu16.04 :worried: 
Will return to this dataset soon, when update my ubuntu to 17.10

**Comment by zelima** [comment]
@AcckiyGerman not really getting the problem here. What that images represent and why do we need to do all that stuff?

re python 3.6 - just use a virtual environment for that http://virtualenvwrapper.readthedocs.io/en/latest/#introduction

**Comment by AcckiyGerman** [comment]
@zelima The picture represents two source files, each one contains two tables with annual and quarterly tables and two outcome files. Arrows represent the dataflow that is happen from source to dest files.

You can see the python dataflow here https://github.com/datasets/gdp-us/blob/f1ea693aacc42c1acf33a41c2b1be7971319d777/scripts/process.py#L24
and here https://github.com/datasets/gdp-us/blob/f1ea693aacc42c1acf33a41c2b1be7971319d777/scripts/process.py#L18

This two functions could be refactored (BTW their output is invalid) and simplified but still I think our pipeline is not ready to automate this dataset

--- 
Actually I think your comment is right - if we don't have to keep the output data format as it was before -  and just unpivot source tables for output - that could be automated

**Comment by zelima** [comment]
@AcckiyGerman so several questions:
* What two sources, what they represent and where they are coming from?
  * also why exactly those two sources and not others?
* Why do we have something with invalid output?
* I see all changes are already pushed to master, Why? Who reviewed the changes?

**Comment by AcckiyGerman** [comment]
WONTFIX:
Freeze automation ATM - the team is changing course! Raise our sails!

**Comment by zelima** [comment]
@AcckiyGerman please close if WONTFIX
